### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by shatfield04970** [mauron85/cordova-plugin-background-geolocation#380]
## Your Environment

* Plugin version: 2.3.3+
* Platform: iOS or Android Android
* OS version: 
* Device manufacturer and model:
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context

Ionic config is:
 ionic info

cli packages: (C:\Users\shatf\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

Plugin list is:
> cordova plugin ls
cordova-plugin-advanced-http 1.11.0 "Advanced HTTP plugin"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.3 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-ext 2.1.1 "Cordova sqlite storage plugin with extra features"
uk.co.workingedge.cordova.plugin.sqliteporter 1.0.2 "sqlite porter"

## Actual Behavior

Build always fails (aapt).  Seems like a couple of Android resources are now missing:, esp:

C:\Users\shatf\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\8fd2e5c5360dfd02afef69d7a5d3d7ce\res\values\values.xml:20:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\shatf\.gradle\caches\transforms-1\files-1.1\support-compat-28.0.0-alpha1.aar\8fd2e5c5360dfd02afef69d7a5d3d7ce\res\values\values.xml:20:5-70: AAPT: error: resource android:attr/ttcIndex not found.

C:\Users\shatf\Projects\t2\platforms\android\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:94: error: resource android:attr/fontVariationSettings not found.
C:\Users\shatf\Projects\t2\platforms\android\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:94: error: resource android:attr/ttcIndex not found.
error: failed linking references.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by SpencerHehl** [comment]
using one of the suggestions in that thread i got it working. in the plugin.xml change framework src="com.android.support:support-v4:+" to framework src="com.android.support:support-v4:23+". builds successfully now.

**Comment by mauron85** [comment]
Yes it's seems latest android support libraries are not compatible. #381 need to be merged.

**Comment by ftunholm** [comment]
Just ran into the same issue @SpencerHehl your solution did not work for me. Might it be because i run cordova-android 7.0.0?

cli packages: (C:\Users\Metadeath\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.10.1
    npm               : 3.10.10
    OS                : Windows 10

Plugins:

    cordova-plugin-device 2.0.1 "Device"
    cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
    cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
    cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
    cordova-plugin-mauron85-background-geolocation 2.3.3 "CDVBackgroundGeolocation"
    cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    cordova-plugin-whitelist 1.3.3 "Whitelist"
    cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"

**Comment by osietrz** [comment]
The solution isn't working for me unfortunately. When I change to the fixed android support version, I start receiving a lot of "Cannot find symbol" errors.

`\platforms\android\app\src\main\java\com\tenforwardconsulting\cordova\BackgroundGeolocationPlugin.java:563: error: cannot find symbol
    @TargetApi(Build.VERSION_CODES.KITKAT)
                                  ^
  symbol:   variable KITKAT
  location: class VERSION_CODES`

**Comment by shatfield04970** [comment]
The proposed fix, changing the framework version to 23+, doesn't appear to
work.  As osietrz states, it generates a bunch of undefined symbols.

A fresh project, at latest revisions, does not build.

Steps to reproduce:

Start a new Ionic project: ionic start projectname blank
Change to directory: cd projectname
Add Android platform: ionic cordova platform add android
Add this one plugin: ionic cordova plugin add
cordova-plugin-mauron85-background-geolocation

Then change the framework settings or not - errors change but neither builds

Attempt build: ionic build android

Build fails.

**Comment by mauron85** [comment]
@shatfield04970 can you plz provide:

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

**Comment by shatfield04970** [comment]
It's pretty much an "all-current" configuration...

ionic info

cli packages: (C:\Users\shatf\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\shatf\AppData\Local\Android\Sdk

Misc:

    backend : pro


PS C:\Users\shatf\Projects\t4> ionic cordova plugin
> cordova plugin ls
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.3
"CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by mauron85** [comment]
Added option to override android library version in config.xml

```
<plugin name="cordova-plugin-mauron85-background-geolocation">
    <!-- may contain other variables as shown above -->
    <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11.0.1" />
    <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
</plugin>
```

This should fix this issue.

**Comment by myamolane** [comment]
hello, i still have this issue
at first, i added this plugin
then added the option in config.xml and then
`cordova platform add android`
`cordova build android`
it still build failed
but change the project.properties file worked
option in config.xml seems doesn't work
is there anything i did wrong?

**Comment by mauron85** [comment]
@myamolane 

config.xml only works when plugin was not installed yet. if plugin was installed any changes to config.xml are ignored. You have to remove plugin and reinstall plugin to reapply changes.
