### ISSUE TITLE
Auto Restarting after called stop() and killed the app

### ISSUE THREAD

**Issue by papattes** [mauron85/cordova-plugin-background-geolocation#552]
## Your Environment
* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: 5.1.1
* Device manufacturer and model: samsung J3
* Running in Simulator: no
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin configuration options: {
		startOnBoot : true,
		saveBatteryOnBackground : true,
		stopOnStillActivity : false,
		stopOnTerminate : false,
		stationaryRadius: 10,
		distanceFilter: 100,
		debug: true,
		notificationsEnabled : false,
		url: scope.url.tasks + '/geofence/test.json?env=_app',
		syncUrl : scope.url.tasks + '/geofence/test.json?env=_app',
		syncThreshold : 1,
		postTemplate: {
			...
		},
		httpHeaders: {
			...
		}
	}
* Link to your project: /

## Context
the geolocation in the background starts again after calling the method stop () and killing the application
## Expected Behavior
the geolocation in the background should not start again alone
## Steps to Reproduce
1. start the application
2. launch geolocation
3. stop geolocation
4. killed the application

## Debug logs
02-12 00:19:00.262 29687-29687/? E/Zygote: MountEmulatedStorage()
02-12 00:19:00.262 29687-29687/? E/Zygote: v2
02-12 00:19:00.262 29687-29687/? I/libpersona: KNOX_SDCARD checking this for 10251
02-12 00:19:00.262 29687-29687/? I/libpersona: KNOX_SDCARD not a persona
02-12 00:19:00.262 29687-29687/? I/SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-J320FN_5.1.1_0073
02-12 00:19:00.272 29687-29687/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
02-12 00:19:00.272 29687-29687/? I/art: Late-enabling -Xcheck:jni
02-12 00:19:00.272 29687-29687/? E/art: setrlimit(RLIMIT_CORE) failed for pid 29687: Operation not permitted
02-12 00:19:00.322 29687-29687/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/fr.pimis.app.users-1/base.apk / 1.0 running in fr.pimis.app.users rsrc of package fr.pimis.app.users
02-12 00:19:00.322 29687-29687/fr.pimis.app.users I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
02-12 00:19:00.332 29687-29687/fr.pimis.app.users D/ResourcesManager: For user 0 new overlays fetched Null
02-12 00:19:00.332 29687-29687/fr.pimis.app.users I/InjectionManager: Inside getClassLibPath caller 
02-12 00:19:00.422 29687-29687/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/fr.pimis.app.users-1/base.apk / 1.0 running in fr.pimis.app.users rsrc of package fr.pimis.app.users
02-12 00:19:00.442 29687-29687/fr.pimis.app.users I/CrashlyticsCore: Initializing Crashlytics 2.6.1.23
02-12 00:19:00.482 29687-29712/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/com.google.android.gms-2/base.apk / 1.0 running in fr.pimis.app.users rsrc of package com.google.android.gms
02-12 00:19:00.492 29687-29704/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:00.492 29687-29704/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isShipBuild true
02-12 00:19:00.492 29687-29704/fr.pimis.app.users I/System.out: (HTTPLog)-Thread-3884-731971529: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
02-12 00:19:00.492 29687-29704/fr.pimis.app.users I/System.out: (HTTPLog)-Thread-3884-731971529: SMARTBONDING_FEATURE_ENABLED is false
02-12 00:19:00.502 29687-29704/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:00.502 29687-29704/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.502 29687-29687/fr.pimis.app.users I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
02-12 00:19:00.512 29687-29712/fr.pimis.app.users D/ResourcesManager: For user 0 new overlays fetched Null
02-12 00:19:00.512 29687-29712/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
02-12 00:19:00.512 29687-29712/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
02-12 00:19:00.552 29687-29704/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.572 29687-29723/fr.pimis.app.users W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
02-12 00:19:00.582 29687-29687/fr.pimis.app.users D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
02-12 00:19:00.582 29687-29687/fr.pimis.app.users I/FirebaseInitProvider: FirebaseApp initialization successful
02-12 00:19:00.592 29687-29728/fr.pimis.app.users W/zze: Application name is not set. Call Builder#setApplicationName.
02-12 00:19:00.622 29687-29727/fr.pimis.app.users W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
02-12 00:19:00.622 29687-29727/fr.pimis.app.users I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
02-12 00:19:00.622 29687-29727/fr.pimis.app.users I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
02-12 00:19:00.643 29687-29687/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/fr.pimis.app.users-1/base.apk / 1.0 running in fr.pimis.app.users rsrc of package fr.pimis.app.users
02-12 00:19:00.653 29687-29734/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:00.653 29687-29734/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.663 29687-29687/fr.pimis.app.users D/InjectionManager: InjectionManager
02-12 00:19:00.663 29687-29733/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:00.663 29687-29687/fr.pimis.app.users D/InjectionManager: fillFeatureStoreMap fr.pimis.app.users
02-12 00:19:00.663 29687-29733/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.663 29687-29687/fr.pimis.app.users I/InjectionManager: Constructor fr.pimis.app.users, Feature store :{}
02-12 00:19:00.663 29687-29687/fr.pimis.app.users I/InjectionManager: featureStore :{}
02-12 00:19:00.703 29687-29734/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.713 29687-29687/fr.pimis.app.users W/art: Failed to open zip archive '/system/framework/timakeystore.jar': I/O Error
02-12 00:19:00.713 29687-29743/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/com.google.android.gms-2/base.apk / 1.0 running in fr.pimis.app.users rsrc of package com.google.android.gms
02-12 00:19:00.713 29687-29733/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:00.713 29687-29743/fr.pimis.app.users D/ResourcesManager: For user 0 new overlays fetched Null
02-12 00:19:00.713 29687-29743/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
02-12 00:19:00.723 29687-29743/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
02-12 00:19:00.763 29687-29687/fr.pimis.app.users I/com.marianhello.bgloc.service.LocationServiceImpl: Creating LocationServiceImpl
02-12 00:19:00.773 29687-29687/fr.pimis.app.users I/com.marianhello.bgloc.PostLocationTask: Creating PostLocationTask
02-12 00:19:00.773 29687-29744/fr.pimis.app.users I/com.marianhello.bgloc.service.LocationServiceImpl: Network condition changed has connectivity: true
02-12 00:19:00.783 29687-29687/fr.pimis.app.users W/com.marianhello.bgloc.service.LocationServiceImpl: Attempt to start unconfigured service. Will use stored or default.
02-12 00:19:00.793 29687-29687/fr.pimis.app.users D/com.marianhello.bgloc.service.LocationServiceImpl: Will start service with: Config[distanceFilter=100 stationaryRadius=10.0 desiredAccuracy=100 interval=600000 fastestInterval=120000 activitiesInterval=10000 isDebugging=true stopOnTerminate=false stopOnStillActivity=false startOnBoot=true startForeground=true notificationsEnabled=false locationProvider=0 nTitle=Background tracking nText=ENABLED nIconLarge= nIconSmall= nIconColor= url=http://pimis.tld/geofence/test.json?env=_app syncUrl=http://pimis.tld/geofence/test.json?env=_app syncThreshold=1 httpHeaders={Content-Type=application/json, X-AccessToken=971fe959f15a292a44c85d8bf6a0e12f} maxLocations=10000 postTemplate={"latitude":"@latitude","pushToken":"cqwylsbmis0:APA91bHsKYZ8_DmaEhenGJP6mDVQ6u3FFoszAgutfmzqOWylhdQhZ3C9xVNHGG8Ld-ca1-AN7Gxv6E1yLNzX2hJaK6X-Md0GvqfNae94g_MDJPhK_sIjbvt8TJlD3pNuxs0Xlo1WupfT","longitude":"@longitude","userUUID":"11E6C025D8D8B6E988A5FA163E724E8F"}]
02-12 00:19:00.803 29687-29687/fr.pimis.app.users I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Creating DistanceFilterLocationProvider
02-12 00:19:00.833 29687-29687/fr.pimis.app.users I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Start recording
02-12 00:19:00.833 29687-29687/fr.pimis.app.users I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Setting pace: false
02-12 00:19:00.893 29687-29687/fr.pimis.app.users I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Setting pace: true
02-12 00:19:01.013 29687-29736/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:01.013 29687-29736/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:01.013 29687-29736/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:01.063 29687-29712/fr.pimis.app.users W/ResourcesManager: getTopLevelResources: /data/app/com.google.android.gms-2/base.apk / 1.0 running in fr.pimis.app.users rsrc of package com.google.android.gms
02-12 00:19:01.073 29687-29712/fr.pimis.app.users D/ResourcesManager: For user 0 new overlays fetched Null
02-12 00:19:01.073 29687-29712/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
02-12 00:19:01.083 29687-29712/fr.pimis.app.users W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
02-12 00:19:01.223 29687-29715/fr.pimis.app.users I/FA: App measurement is starting up, version: 14711
02-12 00:19:01.223 29687-29715/fr.pimis.app.users I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-12 00:19:01.223 29687-29715/fr.pimis.app.users I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app fr.pimis.app.users
02-12 00:19:01.613 29687-29734/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:01.633 29687-29687/fr.pimis.app.users D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[network 42,531157,8,788716 acc=37 et=+1h28m8s281ms {Bundle[mParcelledData.dataSize=328]}] isMoving=true
02-12 00:19:01.653 29687-29687/fr.pimis.app.users D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[network 42,531157,8,788716 acc=37 et=+1h28m8s281ms {Bundle[mParcelledData.dataSize=328]}] isMoving=true
02-12 00:19:01.684 29687-29750/fr.pimis.app.users D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
02-12 00:19:01.724 29687-29750/fr.pimis.app.users I/OpenGLRenderer: Initialized EGL, version 1.4
02-12 00:19:01.724 29687-29750/fr.pimis.app.users D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
02-12 00:19:01.724 29687-29750/fr.pimis.app.users D/OpenGLRenderer: Enabling debug mode 0
02-12 00:19:01.764 29687-29736/fr.pimis.app.users E/GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '225015414575726' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
02-12 00:19:01.804 29687-29704/fr.pimis.app.users E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/fr.pimis.app.users/settings
02-12 00:19:01.804 29687-29704/fr.pimis.app.users E/Answers: Failed to retrieve settings
02-12 00:19:01.814 29687-29706/fr.pimis.app.users W/CrashlyticsCore: Received null settings, skipping report submission!
02-12 00:19:05.167 29687-29687/fr.pimis.app.users D/InputMethodManager: windowDismissed mLockisused = false
02-12 00:19:08.670 29687-29687/fr.pimis.app.users D/InputMethodManager: windowDismissed mLockisused = false
02-12 00:19:16.018 29687-29743/fr.pimis.app.users W/System.err: remove failed: ENOENT (No such file or directory) : /data/data/fr.pimis.app.users/files/AppEventsLogger.persistedevents
02-12 00:19:16.028 29687-29743/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:21.713 29687-29687/fr.pimis.app.users D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[network 42,531157,8,788716 acc=32 et=+1h28m28s402ms {Bundle[mParcelledData.dataSize=328]}] isMoving=true
02-12 00:19:21.733 29687-29687/fr.pimis.app.users I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Setting pace: true
02-12 00:19:21.773 29687-29687/fr.pimis.app.users D/com.marianhello.bgloc.service.LocationServiceImpl: New location BGLocation[network 42,531157,8,788716 id=null acc=32 t=1549927161629 et=+1h28m28s402ms {Bundle[mParcelledData.dataSize=328]} locprov=0]
02-12 00:19:21.803 29687-29745/fr.pimis.app.users D/com.marianhello.bgloc.PostLocationTask: Executing PostLocationTask#postLocation
02-12 00:19:21.803 29687-29745/fr.pimis.app.users D/com.marianhello.bgloc.PostLocationTask: Posting json to url: http://pimis.tld/geofence/test.json?env=_app headers: {Content-Type=application/json, X-AccessToken=971fe959f15a292a44c85d8bf6a0e12f}
02-12 00:19:21.803 29687-29745/fr.pimis.app.users I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
02-12 00:19:21.813 29687-29745/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:21.823 29687-29745/fr.pimis.app.users I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
02-12 00:19:25.236 29687-29687/fr.pimis.app.users D/InputMethodManager: windowDismissed mLockisused = false

**Comment by busaku** [comment]
Dude, its exactly my problem:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/551

I give a little dirty workaround and mauron85 know about the issue :)

**Comment by papattes** [comment]
Effectively !
thank you bro ;)

**Comment by busaku** [comment]
Np 👍 

If u use my workaround don't forget to set the URL to "" after calling .stop()

**Comment by mauron85** [comment]
Don't have a solution just yet, but trying to figure out what is going on here.

Maybe put some light on this issue.

In recent versions plugin is different communication channel between javascript and location service.

It's pure intents now. This much simpler than it was before. However what it does now, it will start android service (not one to one related to location service in this context), when you call any plugin's method (basically configure, start ...) except the stop method. Starting android service doesn't mean that location service start sending locations (you still need to call plugin's start), but it means that android service will accept accept all other commands (like configure, stop) sent internally via intents.

There are only few possible cases, when this unwanted autostart can be triggered.

1. You can plugin's configure and don't call start and then kill your app. With configure you basically start android service (but not location updates as I mentioned above). Then you kill your app.
As android service is set to autorestarts itself when killed it starts itself automatically, but this time it also start location updates (because it assume location updates were active before the service kill/crash).

I understand this is not ideal (didn't see it as problem at first sight). But I'm going to change logic it a a way that configure will not start android service. This should in theory resolve this problem.

What can you do in between the fix is out?

Just don't call configure if you don't plan to call start location tracking. And please let me know, if this my assumption is correct and works for you (it may be also different issue there).

**Comment by mauron85** [comment]
Marking as duplicate of #551, just to have relation between those two.

**Comment by mauron85** [comment]
Should be fixed in v3.0.0.

**Comment by hoisel** [comment]
Hi, the problem persists for me, in v3.0.0

Your Environment
-------------------------------------------------
- Plugin version: 3.0.0
- Platform: Android
- OS version: 8
- Device manufacturer and model: motorola z2 play
- Running in Simulator: no
- Cordova version (cordova -v): 8.11.1
- Cordova platform version (cordova platform ls): android 7.1.4
- Plugin configuration options: {
	- activitiesInterval: 10000
	- debug: false
	- desiredAccuracy: 0
	- distanceFilter: 25
	- fastestInterval: 5000
	- httpHeaders: {}
	- interval: 8000
	- locationProvider: 1
	- maxLocations: 15
	- notificationIconColor: ""
	- notificationIconLarge: ""
	- notificationIconSmall: ""
	- notificationText: ""
	- notificationTitle: "Motorista Online"
	- notificationsEnabled: true
	- postTemplate: {altitude: "@altitude", provider: "@provider", bearing: "@bearing", locationProvider: "@locationProvider", latitude: "@latitude", …}
	- startForeground: true
	- startOnBoot: false
	- stationaryRadius: 25
	- stopOnStillActivity: false
	- stopOnTerminate: false
	- syncThreshold: 5
	- syncUrl: ""
	- url: ""
}

Context logs
-------------------------------------------------
```txt
Stopping service
.SQLiteConfigurationDAO  D  Configuration persisted with rowId = 1
groundGeolocationFacade  D  Service configured with: Config[distanceFilter=25 stationaryRadius=25.0 desiredAccuracy=0 interval=8000 fastestInterval=5000 activitiesInterval=10000 isDebugging=false stopOnTerminate=false stopOnStillActivity=
                            false startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=1 nTitle=Motorista Online nText=Habilitado nIconLarge= nIconSmall= nIconColor= url= syncUrl= syncThreshold=5 httpHeaders={
                            } maxLocations=15 postTemplate=null]
ice.LocationServiceImpl  D  Service in [STARTED] state. cmdId: [4]. startId: [2]
.SQLiteConfigurationDAO  D  Configuration persisted with rowId = 1
groundGeolocationFacade  D  Service configured with: Config[distanceFilter=25 stationaryRadius=25.0 desiredAccuracy=0 interval=8000 fastestInterval=5000 activitiesInterval=10000 isDebugging=false stopOnTerminate=false stopOnStillActivity=
                            false startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=1 nTitle=Motorista Online nText= nIconLarge= nIconSmall= nIconColor= url= syncUrl= syncThreshold=5 httpHeaders={} maxLocat
                            ions=15 postTemplate=null]
gnitionLocationProvider  I  Stop recording
groundGeolocationFacade  I  Attempt to stop bg service
gnitionLocationProvider  I  Start recording
                         D  Start tracking with priority=100 fastestInterval=5000 interval=8000 activitiesInterval=10000 stopOnStillActivity=false
ice.LocationServiceImpl  D  Service in [STARTED] state. cmdId: [4]. startId: [3]
gnitionLocationProvider  I  Stop recording
                         I  Start recording
                         D  Start tracking with priority=100 fastestInterval=5000 interval=8000 activitiesInterval=10000 stopOnStillActivity=false
  SystemWebChromeClient  D  http://localhost:8080/build/main.js: Line 15615 : [BackgroundGeolocation] drawer notification changed to:
               chromium  I  [INFO:CONSOLE(15615)] "[BackgroundGeolocation] drawer notification changed to: ", source: http://localhost:8080/build/main.js (15615)
ice.LocationServiceImpl  D  Service in [STARTED] state. cmdId: [1]. startId: [4]
gnitionLocationProvider  I  Stop recording
  SystemWebChromeClient  D  http://localhost:8080/build/main.js: Line 15668 : [BackgroundGeolocation] current config:
               chromium  I  [INFO:CONSOLE(15668)] "[BackgroundGeolocation] current config:", source: http://localhost:8080/build/main.js (15668)
ice.LocationServiceImpl  I  Destroying LocationServiceImpl
gnitionLocationProvider  I  Destroying ActivityRecognitionLocationProvider
                         I  Stop recording
groundGeolocationFacade  D  Received MSG_ON_SERVICE_STOPPED
  SystemWebChromeClient  D  http://localhost:8080/build/main.js: Line 7285 : [BackgroundGeolocation] event: stop
               chromium  I  [INFO:CONSOLE(7285)] "[BackgroundGeolocation] event: stop ", source: http://localhost:8080/build/main.js (7285)

                            Process br.com.beebee.app:sync created for service br.com.beebee.app/com.marianhello.bgloc.sync.SyncService
                            PID: 32754   UID:    GIDs: 

                 zygote  I  Late-enabling -Xcheck:jni
               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
                 zygote  I  Waiting for a blocking GC ProfileSaver
        CordovaActivity  D  Paused the activity.
groundGeolocationPlugin  I  App will be paused multitasking=true
                 zygote  I  Do partial code cache collection, code=251KB, data=186KB
                         I  After code cache collection, code=251KB, data=186KB
                         I  Increasing code cache capacity to 1024KB
  SystemWebChromeClient  D  http://localhost:8080/build/main.js: Line 7285 : [BackgroundGeolocation] event: background
               chromium  I  [INFO:CONSOLE(7285)] "[BackgroundGeolocation] event: background ", source: http://localhost:8080/build/main.js (7285)
ice.LocationServiceImpl  I  Creating LocationServiceImpl
.bgloc.PostLocationTask  I  Creating PostLocationTask
ice.LocationServiceImpl  I  Network condition changed has connectivity: true
                         D  Service in [NOT STARTED] state. cmdId: [3]. startId: [1]
        CordovaActivity  D  Stopped the activity.
groundGeolocationPlugin  I  App is no longer visible
        CordovaActivity  D  CordovaActivity.onDestroy()
groundGeolocationPlugin  I  Destroying plugin

                            Process br.com.beebee.app:sync (PID: 32754) ended

groundGeolocationFacade  I  Destroying plugin
     CordovaWebViewImpl  D  >>> loadUrl(about:blank)
          cr_AwContents  W  WebView.destroy() called while WebView is still attached to window.
                         W  Application attempted to call on a destroyed WebView
                         W  java.lang.Throwable
                         W      at org.chromium.android_webview.AwContents.f(PG:354)
                         W      at org.chromium.android_webview.AwContents.a(PG:328)
                         W      at org.chromium.android_webview.AwContents.r(PG:630)
                         W      at aDg.loadingStateChanged(PG:136)
                         W      at android.os.MessageQueue.nativePollOnce(Native Method)
                         W      at android.os.MessageQueue.next(MessageQueue.java:325)
                         W      at android.os.Looper.loop(Looper.java:142)
                         W      at android.app.ActivityThread.main(ActivityThread.java:6592)
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         W      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
ice.LocationServiceImpl  D  Task has been removed
                         I  *Continue running in background*
          cr_AwContents  W  Application attempted to call on a destroyed WebView
                         W  java.lang.Throwable
                         W      at org.chromium.android_webview.AwContents.f(PG:354)
                         W      at org.chromium.android_webview.AwContents.a(PG:328)
                         W      at org.chromium.android_webview.AwContents.r(PG:630)
                         W      at aDg.loadingStateChanged(PG:136)
                         W      at android.os.MessageQueue.nativePollOnce(Native Method)
                         W      at android.os.MessageQueue.next(MessageQueue.java:325)
                         W      at android.os.Looper.loop(Looper.java:142)
                         W      at android.app.ActivityThread.main(ActivityThread.java:6592)
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         W      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
ice.LocationServiceImpl  D  Task has been removed
                         I  Continue running in background
                         D  Service in [NOT STARTED] state. cmdId: [6]. startId: [4]

                            Process br.com.beebee.app (PID: 30558) ended
```

**Comment by mauron85** [comment]
Ok. I scanned through your log very carefully and I see you are using `stopOnTerminate: false` which means service will be restarted automatically after app is killed. And I don't see any trace of calling .stop(). Make sure either you call stop before killing app or don't use `stopOnTerminate: false`

**Comment by hoisel** [comment]
Sorry, @mauron85,

The missing log lines:


```txt
                           Process br.com.beebee.app (PID: 4919) ended


                            Process br.com.beebee.app created for service br.com.beebee.app/com.marianhello.bgloc.servi
                            ce.LocationServiceImpl
                            PID: 10995   UID:    GIDs: 

                 zygote  I  Late-enabling -Xcheck:jni
               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
            FirebaseApp  D  com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
                         D  com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
                         D  com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
   FirebaseInitProvider  I  FirebaseApp initialization successful
ice.LocationServiceImpl  I  Creating LocationServiceImpl
.bgloc.PostLocationTask  I  Creating PostLocationTask
ice.LocationServiceImpl  I  Network condition changed has connectivity: true
                         W  Attempt to start unconfigured service. Will use stored or default.
                         D  Will start service with: Config[distanceFilter=25 stationaryRadius=25.0 desiredAccuracy=0 in
                            terval=8000 fastestInterval=5000 activitiesInterval=10000 isDebugging=false stopOnTerminate=
                            false stopOnStillActivity=false startOnBoot=false startForeground=true notificationsEnabled=
                            true locationProvider=1 nTitle=Motorista Online nText= nIconLarge= nIconSmall= nIconColor= u
                            rl= syncUrl= syncThreshold=5 httpHeaders={} maxLocations=15 postTemplate=null]
gnitionLocationProvider  I  Creating ActivityRecognitionLocationProvider
             AudioTrack  I  AUDIO_OUTPUT_FLAG_FAST successful; frameCount 960 -> 960
                         D  Client defaulted notificationFrames to 240 for frameCount 960
gnitionLocationProvider  I  Stop recording
                         I  Start recording
                         D  Connecting to Google Play Services
                         I  Start recording
                         D  Connected to Google Play Services
                         D  Start tracking with priority=100 fastestInterval=5000 interval=8000 activitiesInterval=10000
                             stopOnStillActivity=false
                         D  Location change: Location[fused -20,313497,-40,296780 hAcc=16 et=+4d5h18m21s744ms alt=1.2999
                            999523162842 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
ice.LocationServiceImpl  D  New location BGLocation[fused -20,313497,-40,296780 id=null acc=16 t=1553720343987 et=+4d5h1
                            8m21s744ms alt=1.2999999523162842 {Bundle[mParcelledData.dataSize=52]} locprov=1]
gnitionLocationProvider  D  Location change: Location[fused -20,313497,-40,296780 hAcc=16 et=+4d5h18m39s783ms alt=1.5 vA
                            cc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
ice.LocationServiceImpl  D  New location BGLocation[fused -20,313497,-40,296780 id=null acc=16 t=1553720362026 et=+4d5h1
                            8m39s783ms alt=1.5 {Bundle[mParcelledData.dataSize=52]} locprov=1]

                            Process br.com.beebee.app:sync created for service br.com.beebee.app/com.marianhello.bgloc.
                            sync.SyncService
                            PID: 12218   UID:    GIDs: 

                 zygote  I  Late-enabling -Xcheck:jni
               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
gnitionLocationProvider  D  Location change: Location[fused -20,313497,-40,296780 hAcc=16 et=+4d5h18m57s841ms alt=1.2999
                            999523162842 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
ice.LocationServiceImpl  D  New location BGLocation[fused -20,313497,-40,296780 id=null acc=16 t=1553720380084 et=+4d5h1
                            8m57s841ms alt=1.2999999523162842 {Bundle[mParcelledData.dataSize=52]} locprov=1]

```

**Comment by mauron85** [comment]
Yes, you're right. Issue is still there. Reopening.

**Comment by mauron85** [comment]
Please try version 3.0.1. It shouldn't start services on app visibility change, like app moving from foreground to background.

There is still once case, when service will be started automatically -> when you call `BackgroundGeolocation.headlessTask`. Just make sure you call it only when you already called `BackgroundGeolocation.start`.

**Comment by hoisel** [comment]
Thanks, now it was fixed for me!
